"""Public API for dms_parser."""

from __future__ import annotations

import logging

from dms_parser.builders import build_mavedb_dataset, build_proteingym_dataset
from dms_parser.cache import CacheManifest, FilesystemCache
from dms_parser.catalog import DatasetRecord, get_dataset_metadata, list_datasets
from dms_parser.exceptions import (
    CacheError,
    CatalogError,
    CorruptCacheManifestError,
    DMSParserError,
    DatasetNotFoundError,
    DownloadError,
    FileFormatError,
    InvalidCacheEntryError,
    InvalidCatalogQueryError,
    InvalidDatasetError,
    InvalidHGVSVariantError,
    InvalidVariantError,
    MissingWildTypeError,
    MutationApplicationError,
    SequenceValidationError,
    SourceConfigurationError,
    UnknownSourceResourceError,
    UnsupportedSourceResourceError,
    UnsupportedVariantError,
)
from dms_parser.fetch import fetch_to_cache
from dms_parser.io import (
    download_file,
    ensure_local_copy,
    infer_filename_from_url,
    read_table,
    write_table,
)
from dms_parser.parsing import (
    apply_mutations,
    count_mutations,
    explode_mutations,
    extract_mutation_tokens,
    extract_positions,
    hgvs_pro_is_indel,
    hgvs_to_sequence,
    is_wildtype_variant,
    parse_hgvs_pro,
    parse_mavedb_hgvs_series,
    parse_variant,
    parse_variant_series,
    parse_variant_token,
    read_fasta_one,
    translate_dna,
    variant_to_sequence,
)
from dms_parser.transforms import (
    add_minmax,
    add_pseudo_binary_label,
    add_wt_relative_score,
    add_zscore,
    compute_wt_score,
)
from dms_parser.sources.mavedb_catalog import MaveDBCatalog
from dms_parser.sources.proteingym_catalog import ProteinGymCatalog
from dms_parser.sources.proteingym_resources import (
    PROTEINGYM_RESOURCES,
    ProteinGymResource,
    get_proteingym_resource,
    list_proteingym_resources,
)
from dms_parser.validation import (
    count_invalid_sequences,
    has_wildtype_row,
    validate_column_non_empty,
    validate_consistent_sequence_lengths,
    validate_n_mutations_column,
    validate_required_columns,
    validate_score_column,
    validate_sequence_column,
    validate_standard_dataset,
    validate_status_column,
    validate_variant_column,
    validate_wt_presence,
    validate_wt_sequence,
)

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

__all__ = [
    "build_mavedb_dataset",
    "build_proteingym_dataset",
    "DatasetRecord",
    "MaveDBCatalog",
    "ProteinGymCatalog",
    "ProteinGymResource",
    "PROTEINGYM_RESOURCES",
    "get_proteingym_resource",
    "list_proteingym_resources",
    "list_datasets",
    "get_dataset_metadata",
    "FilesystemCache",
    "CacheManifest",
    "fetch_to_cache",
    "parse_variant",
    "parse_variant_token",
    "parse_variant_series",
    "parse_hgvs_pro",
    "parse_mavedb_hgvs_series",
    "count_mutations",
    "is_wildtype_variant",
    "explode_mutations",
    "extract_positions",
    "extract_mutation_tokens",
    "hgvs_pro_is_indel",
    "apply_mutations",
    "variant_to_sequence",
    "hgvs_to_sequence",
    "read_fasta_one",
    "translate_dna",
    "compute_wt_score",
    "add_wt_relative_score",
    "add_pseudo_binary_label",
    "add_zscore",
    "add_minmax",
    "download_file",
    "infer_filename_from_url",
    "ensure_local_copy",
    "read_table",
    "write_table",
    "validate_required_columns",
    "validate_column_non_empty",
    "validate_score_column",
    "validate_variant_column",
    "validate_status_column",
    "validate_wt_sequence",
    "validate_wt_presence",
    "validate_n_mutations_column",
    "validate_sequence_column",
    "validate_consistent_sequence_lengths",
    "validate_standard_dataset",
    "has_wildtype_row",
    "count_invalid_sequences",
    "DMSParserError",
    "CacheError",
    "CatalogError",
    "InvalidCacheEntryError",
    "CorruptCacheManifestError",
    "InvalidCatalogQueryError",
    "DatasetNotFoundError",
    "SourceConfigurationError",
    "UnknownSourceResourceError",
    "UnsupportedSourceResourceError",
    "InvalidDatasetError",
    "MissingWildTypeError",
    "InvalidVariantError",
    "InvalidHGVSVariantError",
    "UnsupportedVariantError",
    "SequenceValidationError",
    "MutationApplicationError",
    "DownloadError",
    "FileFormatError",
]
